import { test, expect, APIRequestContext, request } from '@playwright/test';
import { randomUUID } from 'node:crypto';

// Generated by test-builder from docs/test-scenarios/orders/tester-orders-2026-04-20.md
// Flow: F-01 (submit happy path) + F-02 (payment declined)
// Layer: API (APIRequestContext — no browser)
//
// Credentials via env — never hardcode (see CLAUDE.md).
// Seed data assumed provisioned by scripts/orders-reset.sh.

const BASE_URL = process.env.API_BASE_URL ?? 'http://localhost:8080';

async function authedContext(email: string, password: string): Promise<APIRequestContext> {
  const ctx = await request.newContext({ baseURL: BASE_URL });
  const login = await ctx.post('/api/v1/auth/login', { data: { email, password } });
  expect(login.ok()).toBeTruthy();
  const { token } = await login.json();
  return request.newContext({
    baseURL: BASE_URL,
    extraHTTPHeaders: {
      Authorization: `Bearer ${token}`,
      'X-Request-ID': `pw-${randomUUID()}`,
    },
  });
}

test.describe('Orders F-01 API — submit happy path', () => {
  test('ORDERS-HP-001 submit single-item order', async () => {
    const ctx = await authedContext(
      process.env.TEST_CUSTOMER_NEW!,
      process.env.TEST_CUSTOMER_NEW_PASSWORD!,
    );
    const idemKey = randomUUID();

    const res = await ctx.post('/api/v1/orders', {
      headers: { 'Idempotency-Key': idemKey },
      data: {
        cart_snapshot: {
          items: [{ sku: 'SKU-ABC-001', quantity: 1, unit_price: 25.0 }],
          total: 25.0,
        },
        payment_token: process.env.PM_SUCCESS!,
        shipping_address_id: process.env.TEST_ADDRESS_ID!,
      },
    });

    expect(res.status()).toBe(201);
    const body = await res.json();
    expect(body.state).toBe('CONFIRMED');
    expect(body.order_number).toMatch(/^ORD-\d{4}-\d{5}$/);
    expect(body.flagged).toBe(false);
    await ctx.dispose();
  });

  test('ORDERS-HP-003 order > USD 1,000 flagged', async () => {
    const ctx = await authedContext(
      process.env.TEST_CUSTOMER_NEW!,
      process.env.TEST_CUSTOMER_NEW_PASSWORD!,
    );
    const res = await ctx.post('/api/v1/orders', {
      headers: { 'Idempotency-Key': randomUUID() },
      data: {
        cart_snapshot: {
          items: [{ sku: 'SKU-HIGH-VAL', quantity: 1, unit_price: 1250.0 }],
          total: 1250.0,
        },
        payment_token: process.env.PM_SUCCESS!,
        shipping_address_id: process.env.TEST_ADDRESS_ID!,
      },
    });
    expect(res.status()).toBe(201);
    const body = await res.json();
    expect(body.state).toBe('CONFIRMED');
    expect(body.flagged).toBe(true);
    await ctx.dispose();
  });
});

test.describe('Orders F-02 API — payment declined + idempotency', () => {
  test('ORDERS-BR-003 payment declined releases inventory', async () => {
    const ctx = await authedContext(
      process.env.TEST_CUSTOMER_DECLINE!,
      process.env.TEST_CUSTOMER_DECLINE_PASSWORD!,
    );
    const res = await ctx.post('/api/v1/orders', {
      headers: { 'Idempotency-Key': randomUUID() },
      data: {
        cart_snapshot: {
          items: [{ sku: 'SKU-ABC-001', quantity: 1, unit_price: 25.0 }],
          total: 25.0,
        },
        payment_token: process.env.PM_DECLINE!,
        shipping_address_id: process.env.TEST_ADDRESS_ID!,
      },
    });
    expect(res.status()).toBe(402);
    const body = await res.json();
    expect(body.code).toBe('PAYMENT_DECLINED');
    expect(body.trace_id).toBeTruthy();
    await ctx.dispose();
  });

  test('ORDERS-IDEM-001 replay same key < 24h returns same order', async () => {
    const ctx = await authedContext(
      process.env.TEST_CUSTOMER_NEW!,
      process.env.TEST_CUSTOMER_NEW_PASSWORD!,
    );
    const idemKey = randomUUID();
    const payload = {
      cart_snapshot: {
        items: [{ sku: 'SKU-ABC-001', quantity: 1, unit_price: 25.0 }],
        total: 25.0,
      },
      payment_token: process.env.PM_SUCCESS!,
      shipping_address_id: process.env.TEST_ADDRESS_ID!,
    };

    const first = await ctx.post('/api/v1/orders', {
      headers: { 'Idempotency-Key': idemKey },
      data: payload,
    });
    expect(first.status()).toBe(201);
    const firstBody = await first.json();

    const replay = await ctx.post('/api/v1/orders', {
      headers: { 'Idempotency-Key': idemKey },
      data: payload,
    });
    expect(replay.status()).toBe(201);
    const replayBody = await replay.json();
    expect(replayBody.order_id).toBe(firstBody.order_id);
    await ctx.dispose();
  });

  test('ORDERS-SP-001 missing Idempotency-Key returns VALIDATION_ERROR', async () => {
    const ctx = await authedContext(
      process.env.TEST_CUSTOMER_NEW!,
      process.env.TEST_CUSTOMER_NEW_PASSWORD!,
    );
    const res = await ctx.post('/api/v1/orders', {
      data: {
        cart_snapshot: {
          items: [{ sku: 'SKU-ABC-001', quantity: 1, unit_price: 25.0 }],
          total: 25.0,
        },
        payment_token: process.env.PM_SUCCESS!,
        shipping_address_id: process.env.TEST_ADDRESS_ID!,
      },
    });
    expect(res.status()).toBe(400);
    const body = await res.json();
    expect(body.code).toBe('VALIDATION_ERROR');
    await ctx.dispose();
  });
});
