import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';

// Generated by test-builder from docs/test-scenarios/orders/tester-orders-2026-04-20.md
// Flow: F-01 (submit happy path) — FE layer (browser E2E)
// UI Selectors sourced verbatim from docs/fr/orders/fr-order-submit.md §UI Selectors.

test.beforeEach(async ({ page, context }) => {
  // X-Request-ID injected on every request for log traceability.
  await context.route('**/*', (route) => {
    const headers = { ...route.request().headers(), 'X-Request-ID': `pw-${randomUUID()}` };
    route.continue({ headers });
  });
  await page.goto('/login');
  await page.getByTestId('login-email').fill(process.env.TEST_CUSTOMER_NEW!);
  await page.getByTestId('login-password').fill(process.env.TEST_CUSTOMER_NEW_PASSWORD!);
  await page.getByTestId('login-submit').click();
  await expect(page).toHaveURL(/\/home$/);
});

test.describe('Orders F-01 FE — checkout → confirmation', () => {
  test('ORDERS-HP-001 UI: submit single-item order, see confirmation', async ({ page }) => {
    await page.goto('/checkout?cart=seed-abc-001');

    // testid from FR §UI Selectors — verbatim
    await expect(page.getByTestId('checkout-total')).toContainText('25.00');
    await page.getByTestId('place-order-btn').click();

    await expect(page).toHaveURL(/\/orders\/[\w-]+$/);
    await expect(page.getByTestId('order-confirmation-banner')).toBeVisible();
    await expect(page.getByTestId('order-confirmation-number')).toContainText(/^ORD-\d{4}-\d{5}$/);
  });

  test('ORDERS-BR-003 UI: payment declined shows error banner with code', async ({ page }) => {
    // Log in as decline-configured customer
    await page.goto('/logout');
    await page.goto('/login');
    await page.getByTestId('login-email').fill(process.env.TEST_CUSTOMER_DECLINE!);
    await page.getByTestId('login-password').fill(process.env.TEST_CUSTOMER_DECLINE_PASSWORD!);
    await page.getByTestId('login-submit').click();

    await page.goto('/checkout?cart=seed-abc-001');
    await page.getByTestId('place-order-btn').click();

    await expect(page.getByTestId('checkout-error-banner')).toBeVisible();
    await expect(page.getByTestId('checkout-error-code')).toHaveText('PAYMENT_DECLINED');
    await expect(page.getByTestId('retry-payment-btn')).toBeEnabled();
  });

  // Skipped: requires catalog background flip — not expressible with default seed.
  test.fixme('ORDERS-BR-001 UI: price drift shows PRICE_DRIFT banner', async () => {});
});
